# Use UBI9 as base image
FROM registry.access.redhat.com/ubi9/ubi

# add more repository
RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
RUN dnf -y install https://rpms.remirepo.net/enterprise/remi-release-9.rpm

# Update Software repository
RUN dnf -y update

# Install PHP and necessary PHP extensions
RUN dnf install -y unzip 
RUN dnf module install -y php:remi-7.4
RUN dnf --enablerepo=remi install -y php-intl

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy your PHP CodeIgniter 4 application into the Docker image
COPY . /application

# Set the working directory
WORKDIR /application

# Install dependencies
RUN composer install

RUN cp vendor/codeigniter4/framework/public/index.php public/index.php
RUN cp vendor/codeigniter4/framework/spark spark

# Run your PHP CodeIgniter 4 application
CMD ["php", "spark", "serve"]
